description: |
  Configure the NVMRC_VERSION environment variable
  based on the .nvmrc file in the project root directory.
steps:
  - run:
      name: Configure NVMRC
      command: |
        if [ -z "$NVMRC_VERSION" ]; then
          echo "==> Configuring NVMRC_VERSION!"

          export ENV_DOT_PROFILE=$HOME/.profile
          touch $ENV_DOT_PROFILE

          export NVMRC_VERSION=$(cat $CIRCLE_WORKING_DIRECTORY/.nvmrc)
          echo "export NVMRC_VERSION=$NVMRC_VERSION" >> $ENV_DOT_PROFILE
        fi
        echo "NVMRC_VERSION=$NVMRC_VERSION"
